"""Bundle course.json, bag.json and strategy.json into data.js, which index.html loads.

Run from the golf/ folder after editing any of the JSON files:  python3 scripts/build_data.py
(A browser can't read JSON files from disk when index.html is opened by double-click, but it can
load a script, so the data travels inside data.js.)
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def main():
    data = {name: json.loads((ROOT / f"{name}.json").read_text()) for name in ("course", "bag", "strategy")}
    js = "// Generated by scripts/build_data.py from course.json, bag.json and strategy.json. Don't edit by hand.\n"
    js += "window.OLIVAR = " + json.dumps(data, ensure_ascii=False, separators=(",", ":")) + ";\n"
    (ROOT / "data.js").write_text(js)
    print(f"data.js written ({len(js) // 1024} KB)")


if __name__ == "__main__":
    main()
